# Generated by Django 4.0.2 on 2022-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OT', 'Other'), ('SF', 'Shoots forward'), ('ML', 'Melee'), ('FB', 'Shoots forward or backward'), ('ST', 'Status'), ('DB', 'Drops backward'), ('LS', 'Lock-on shot')], max_length=2),
        ),
    ]
