# Generated by Django 4.0.2 on 2022-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0007_remove_order_item_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Melee'), ('DB', 'Drops backward'), ('SF', 'Shoots forward'), ('LS', 'Lock-on shot'), ('ST', 'Status'), ('OT', 'Other'), ('FB', 'Shoots forward or backward')], max_length=2),
        ),
    ]
