# Generated by Django 4.0.2 on 2022-02-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0008_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mkmrkt.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mkmrkt.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Melee'), ('ST', 'Status'), ('DB', 'Drops backward'), ('LS', 'Lock-on shot'), ('SF', 'Shoots forward'), ('FB', 'Shoots forward or backward'), ('OT', 'Other')], max_length=2),
        ),
    ]
