# Generated by Django 4.0.2 on 2022-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0009_delete_address_rename_start_date_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FB', 'Shoots forward or backward'), ('DB', 'Drops backward'), ('ML', 'Melee'), ('ST', 'Status'), ('SF', 'Shoots forward'), ('LS', 'Lock-on shot'), ('OT', 'Other')], max_length=2),
        ),
    ]
