# Generated by Django 4.0.2 on 2022-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SF', 'Shoots forward'), ('FB', 'Shoots forward or backward'), ('DB', 'Drops backward'), ('OT', 'Other'), ('LS', 'Lock-on shot'), ('ST', 'Status'), ('ML', 'Melee')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
