# Generated by Django 4.0.2 on 2022-02-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0015_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ST', 'Status'), ('LS', 'Lock-on shot'), ('OT', 'Other'), ('SF', 'Shoots forward'), ('ML', 'Melee'), ('DB', 'Drops backward'), ('FB', 'Shoots forward or backward')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
