# Generated by Django 4.0.2 on 2022-02-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0019_order_created_by_orderitem_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Melee'), ('ST', 'Status'), ('SF', 'Shoots forward'), ('LS', 'Lock-on shot'), ('DB', 'Drops backward'), ('FB', 'Shoots forward or backward'), ('OT', 'Other')], max_length=2),
        ),
    ]
