# Generated by Django 4.0.2 on 2022-02-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0020_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SF', 'Shoots forward'), ('OT', 'Other'), ('DB', 'Drops backward'), ('FB', 'Shoots forward or backward'), ('ML', 'Melee'), ('LS', 'Lock-on shot'), ('ST', 'Status')], max_length=2),
        ),
    ]
