# Generated by Django 4.0.2 on 2022-02-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0021_remove_order_created_by_remove_orderitem_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DB', 'Drops backward'), ('SF', 'Shoots forward'), ('LS', 'Lock-on shot'), ('ST', 'Status'), ('OT', 'Other'), ('FB', 'Shoots forward or backward'), ('ML', 'Melee')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
    ]
