# Generated by Django 4.0.2 on 2022-02-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0022_alter_product_category_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lock-on shot'), ('FB', 'Shoots forward or backward'), ('ML', 'Melee'), ('OT', 'Other'), ('SF', 'Shoots forward'), ('ST', 'Status'), ('DB', 'Drops backward')], max_length=2),
        ),
    ]
