# Generated by Django 4.0.2 on 2022-02-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0024_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DB', 'Drops backward'), ('SF', 'Shoots forward'), ('ST', 'Status'), ('OT', 'Other'), ('LS', 'Lock-on shot'), ('ML', 'Melee'), ('FB', 'Shoots forward or backward')], max_length=2),
        ),
    ]
