# Generated by Django 4.0.2 on 2022-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0027_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ST', 'Status'), ('LS', 'Lock-on shot'), ('FB', 'Shoots forward or backward'), ('OT', 'Other'), ('SF', 'Shoots forward'), ('DB', 'Drops backward'), ('ML', 'Melee')], max_length=2),
        ),
    ]
