# Generated by Django 4.0.2 on 2022-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0029_order_user_orderitem_user_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OT', 'Other'), ('DB', 'Drops backward'), ('FB', 'Shoots forward or backward'), ('ML', 'Melee'), ('LS', 'Lock-on shot'), ('ST', 'Status'), ('SF', 'Shoots forward')], max_length=2),
        ),
    ]
