# Generated by Django 4.0.2 on 2022-02-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0036_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkmrkt.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkmrkt.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DB', 'Drops backward'), ('OT', 'Other'), ('FB', 'Shoots forward or backward'), ('LS', 'Lock-on shot'), ('ST', 'Status'), ('SF', 'Shoots forward'), ('ML', 'Melee')], max_length=2),
        ),
    ]
