# Generated by Django 4.0.2 on 2022-02-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0037_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ST', 'Status'), ('SF', 'Shoots forward'), ('OT', 'Other'), ('ML', 'Melee'), ('FB', 'Shoots forward or backward'), ('LS', 'Lock-on shot'), ('DB', 'Drops backward')], max_length=2),
        ),
    ]
