# Generated by Django 4.0.2 on 2022-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0039_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Melee'), ('FB', 'Shoots forward or backward'), ('SF', 'Shoots forward'), ('LS', 'Lock-on shot'), ('OT', 'Other'), ('ST', 'Status'), ('DB', 'Drops backward')], max_length=2),
        ),
    ]
