# Generated by Django 4.0.2 on 2022-02-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0040_remove_order_user_remove_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ST', 'Status'), ('DB', 'Drops backward'), ('LS', 'Lock-on shot'), ('SF', 'Shoots forward'), ('OT', 'Other'), ('ML', 'Melee'), ('FB', 'Shoots forward or backward')], max_length=2),
        ),
    ]
