# Generated by Django 4.0.2 on 2022-02-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0042_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FB', 'Shoots forward or backward'), ('LS', 'Lock-on shot'), ('ST', 'Status'), ('ML', 'Melee'), ('OT', 'Other'), ('SF', 'Shoots forward'), ('DB', 'Drops backward')], max_length=2),
        ),
    ]
