# Generated by Django 4.0.2 on 2022-02-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmrkt', '0045_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SF', 'Shoots forward'), ('ST', 'Status'), ('LS', 'Lock-on shot'), ('OT', 'Other'), ('FB', 'Shoots forward or backward'), ('ML', 'Melee'), ('DB', 'Drops backward')], max_length=2),
        ),
    ]
