export const PRODUCT_LOADING_TYPE = 'PRODUCT_LOADING_TYPE';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_BY_SLUG = 'GET_PRODUCT_BY_SLUG';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
